jtype: Flow
version: '1'
with:
  port: 51000
  protocol: http
executors:
  - name: clip_t
    uses:
      jtype: CLIPEncoder
      with:
        name: RN50::openai
      metas:
        py_modules:
          - clip_server.executors.clip_torch